import { supportedCountries, type CountryCode } from "./countries";
import type { HubTransportType } from "./transport";

export type TransportHubKind = "airport" | "port";

export type TransportHub = {
    id: string;
    countryCode: CountryCode;
    kind: TransportHubKind;
    code: string;
    name: string;
    region: string;
    aliases: readonly string[];
    coordinates: {
        latitude: number;
        longitude: number;
    };
};

type HubSeed = readonly [
    id: string,
    kind: TransportHubKind,
    code: string,
    name: string,
    region: string,
    longitude: number,
    latitude: number,
    aliases?: readonly string[],
];

const hubSeeds: Record<CountryCode, readonly HubSeed[]> = {
    KR: [
        [
            "kr-icn",
            "airport",
            "ICN",
            "인천국제공항",
            "인천",
            126.4505,
            37.4692,
            ["서울", "수도권", "seoul", "incheon"],
        ],
        [
            "kr-gmp",
            "airport",
            "GMP",
            "김포국제공항",
            "서울",
            126.791,
            37.5583,
            ["김포", "수도권", "seoul"],
        ],
        [
            "kr-cju",
            "airport",
            "CJU",
            "제주국제공항",
            "제주",
            126.493,
            33.5104,
            ["제주도", "jeju"],
        ],
        [
            "kr-pus",
            "airport",
            "PUS",
            "김해국제공항",
            "부산",
            128.9382,
            35.1795,
            ["김해", "경남", "busan"],
        ],
        [
            "kr-tae",
            "airport",
            "TAE",
            "대구국제공항",
            "대구",
            128.6379,
            35.8941,
            ["경북", "daegu"],
        ],
        [
            "kr-cjj",
            "airport",
            "CJJ",
            "청주국제공항",
            "청주",
            127.4987,
            36.7166,
            ["대전", "충청", "cheongju"],
        ],
        [
            "kr-kwj",
            "airport",
            "KWJ",
            "광주공항",
            "광주",
            126.8089,
            35.1264,
            ["전남", "gwangju"],
        ],
        [
            "kr-rsu",
            "airport",
            "RSU",
            "여수공항",
            "여수",
            127.6169,
            34.8423,
            ["순천", "전남", "yeosu"],
        ],
        [
            "kr-yny",
            "airport",
            "YNY",
            "양양국제공항",
            "양양",
            128.6692,
            38.0613,
            ["속초", "강원", "yangyang"],
        ],
        [
            "kr-incheon-port",
            "port",
            "INCHEON",
            "인천항",
            "인천",
            126.6033,
            37.4522,
            ["서울", "수도권", "incheon"],
        ],
        [
            "kr-busan-port",
            "port",
            "BUSAN",
            "부산항",
            "부산",
            129.0403,
            35.1038,
            ["경남", "busan"],
        ],
        [
            "kr-jeju-port",
            "port",
            "JEJU",
            "제주항",
            "제주",
            126.5339,
            33.5186,
            ["제주도", "jeju"],
        ],
        [
            "kr-mokpo-port",
            "port",
            "MOKPO",
            "목포항",
            "목포",
            126.3817,
            34.7833,
            ["전남", "mokpo"],
        ],
        [
            "kr-sokcho-port",
            "port",
            "SOKCHO",
            "속초항",
            "속초",
            128.5942,
            38.2084,
            ["강원", "sokcho"],
        ],
        [
            "kr-pohang-port",
            "port",
            "POHANG",
            "포항항",
            "포항",
            129.3917,
            36.0417,
            ["경북", "pohang"],
        ],
    ],
    JP: [
        [
            "jp-hnd",
            "airport",
            "HND",
            "하네다 공항",
            "도쿄",
            139.7798,
            35.5494,
            ["동경", "tokyo"],
        ],
        [
            "jp-nrt",
            "airport",
            "NRT",
            "나리타 국제공항",
            "도쿄",
            140.3929,
            35.772,
            ["나리타", "치바", "동경", "tokyo"],
        ],
        [
            "jp-kix",
            "airport",
            "KIX",
            "간사이 국제공항",
            "오사카",
            135.244,
            34.4347,
            ["교토", "고베", "간사이", "osaka", "kyoto"],
        ],
        [
            "jp-itm",
            "airport",
            "ITM",
            "오사카 국제공항",
            "오사카",
            135.4382,
            34.7855,
            ["이타미", "교토", "고베", "osaka", "kyoto"],
        ],
        [
            "jp-fuk",
            "airport",
            "FUK",
            "후쿠오카 공항",
            "후쿠오카",
            130.451,
            33.5859,
            ["하카타", "규슈", "fukuoka"],
        ],
        [
            "jp-cts",
            "airport",
            "CTS",
            "신치토세 공항",
            "삿포로",
            141.6923,
            42.7752,
            ["홋카이도", "치토세", "sapporo"],
        ],
        [
            "jp-oka",
            "airport",
            "OKA",
            "나하 공항",
            "오키나와",
            127.6459,
            26.1958,
            ["나하", "okinawa"],
        ],
        [
            "jp-ngo",
            "airport",
            "NGO",
            "주부 국제공항",
            "나고야",
            136.8054,
            34.8584,
            ["아이치", "nagoya"],
        ],
        [
            "jp-hij",
            "airport",
            "HIJ",
            "히로시마 공항",
            "히로시마",
            132.9194,
            34.4361,
            ["hiroshima"],
        ],
        [
            "jp-hakata-port",
            "port",
            "HAKATA",
            "하카타항",
            "후쿠오카",
            130.401,
            33.606,
            ["하카타", "규슈", "fukuoka"],
        ],
        [
            "jp-osaka-port",
            "port",
            "OSAKA",
            "오사카항",
            "오사카",
            135.433,
            34.65,
            ["간사이", "osaka"],
        ],
        [
            "jp-shimonoseki-port",
            "port",
            "SHIMONOSEKI",
            "시모노세키항",
            "시모노세키",
            130.933,
            33.95,
            ["야마구치", "shimonoseki"],
        ],
        [
            "jp-kobe-port",
            "port",
            "KOBE",
            "고베항",
            "고베",
            135.1955,
            34.6825,
            ["오사카", "간사이", "kobe"],
        ],
        [
            "jp-yokohama-port",
            "port",
            "YOKOHAMA",
            "요코하마항",
            "요코하마",
            139.6488,
            35.4516,
            ["도쿄", "가나가와", "yokohama"],
        ],
        [
            "jp-sakaiminato-port",
            "port",
            "SAKAIMINATO",
            "사카이미나토항",
            "돗토리",
            133.247,
            35.545,
            ["요나고", "sakaiminato"],
        ],
    ],
    VN: [
        [
            "vn-dad",
            "airport",
            "DAD",
            "다낭 국제공항",
            "다낭",
            108.2022,
            16.0439,
            ["da nang", "danang"],
        ],
        [
            "vn-han",
            "airport",
            "HAN",
            "노이바이 국제공항",
            "하노이",
            105.8072,
            21.2187,
            ["hanoi"],
        ],
        [
            "vn-sgn",
            "airport",
            "SGN",
            "떤선녓 국제공항",
            "호치민",
            106.6519,
            10.8188,
            ["사이공", "ho chi minh", "saigon"],
        ],
        [
            "vn-cxr",
            "airport",
            "CXR",
            "깜라인 국제공항",
            "나트랑",
            109.2194,
            11.9982,
            ["깜란", "nha trang"],
        ],
        [
            "vn-pqc",
            "airport",
            "PQC",
            "푸꾸옥 국제공항",
            "푸꾸옥",
            103.9931,
            10.1698,
            ["phu quoc"],
        ],
        [
            "vn-hui",
            "airport",
            "HUI",
            "푸바이 국제공항",
            "후에",
            107.7028,
            16.4015,
            ["hue"],
        ],
        [
            "vn-danang-port",
            "port",
            "DANANG",
            "다낭항",
            "다낭",
            108.217,
            16.12,
            ["da nang", "danang"],
        ],
        [
            "vn-saigon-port",
            "port",
            "SAIGON",
            "사이공항",
            "호치민",
            106.718,
            10.76,
            ["사이공", "ho chi minh", "saigon"],
        ],
        [
            "vn-haiphong-port",
            "port",
            "HAIPHONG",
            "하이퐁항",
            "하이퐁",
            106.69,
            20.86,
            ["hai phong"],
        ],
        [
            "vn-nhatrang-port",
            "port",
            "NHA TRANG",
            "나트랑항",
            "나트랑",
            109.215,
            12.197,
            ["nha trang"],
        ],
    ],
    CN: [
        [
            "cn-pvg",
            "airport",
            "PVG",
            "상하이 푸둥 국제공항",
            "상하이",
            121.8052,
            31.1443,
            ["푸동", "shanghai"],
        ],
        [
            "cn-sha",
            "airport",
            "SHA",
            "상하이 훙차오 국제공항",
            "상하이",
            121.3363,
            31.1979,
            ["홍차오", "shanghai"],
        ],
        [
            "cn-pek",
            "airport",
            "PEK",
            "베이징 수도 국제공항",
            "베이징",
            116.5975,
            40.0799,
            ["북경", "beijing"],
        ],
        [
            "cn-pkx",
            "airport",
            "PKX",
            "베이징 다싱 국제공항",
            "베이징",
            116.4109,
            39.5098,
            ["다싱", "북경", "beijing"],
        ],
        [
            "cn-tao",
            "airport",
            "TAO",
            "칭다오 자오둥 국제공항",
            "칭다오",
            120.3744,
            36.3619,
            ["청도", "qingdao"],
        ],
        [
            "cn-can",
            "airport",
            "CAN",
            "광저우 바이윈 국제공항",
            "광저우",
            113.2988,
            23.3924,
            ["광주", "guangzhou"],
        ],
        [
            "cn-szx",
            "airport",
            "SZX",
            "선전 바오안 국제공항",
            "선전",
            113.8107,
            22.6393,
            ["심천", "shenzhen"],
        ],
        [
            "cn-xiy",
            "airport",
            "XIY",
            "시안 셴양 국제공항",
            "시안",
            108.7516,
            34.4471,
            ["서안", "xian"],
        ],
        [
            "cn-ctu",
            "airport",
            "CTU",
            "청두 솽류 국제공항",
            "청두",
            103.9471,
            30.5785,
            ["성도", "chengdu"],
        ],
        [
            "cn-tfu",
            "airport",
            "TFU",
            "청두 톈푸 국제공항",
            "청두",
            104.4413,
            30.319,
            ["톈푸", "성도", "chengdu"],
        ],
        [
            "cn-shanghai-port",
            "port",
            "SHANGHAI",
            "상하이항",
            "상하이",
            121.5,
            31.35,
            ["shanghai"],
        ],
        [
            "cn-qingdao-port",
            "port",
            "QINGDAO",
            "칭다오항",
            "칭다오",
            120.31,
            36.06,
            ["청도", "qingdao"],
        ],
        [
            "cn-weihai-port",
            "port",
            "WEIHAI",
            "웨이하이항",
            "웨이하이",
            122.11,
            37.5,
            ["위해", "weihai"],
        ],
        [
            "cn-tianjin-port",
            "port",
            "TIANJIN",
            "톈진항",
            "톈진",
            117.75,
            38.99,
            ["천진", "베이징", "tianjin"],
        ],
        [
            "cn-shenzhen-port",
            "port",
            "SHENZHEN",
            "선전항",
            "선전",
            114.26,
            22.57,
            ["심천", "shenzhen"],
        ],
    ],
    TH: [
        [
            "th-bkk",
            "airport",
            "BKK",
            "수완나품 국제공항",
            "방콕",
            100.7501,
            13.69,
            ["bangkok"],
        ],
        [
            "th-dmk",
            "airport",
            "DMK",
            "돈므앙 국제공항",
            "방콕",
            100.6068,
            13.9126,
            ["돈무앙", "bangkok"],
        ],
        [
            "th-hkt",
            "airport",
            "HKT",
            "푸껫 국제공항",
            "푸껫",
            98.3169,
            8.1132,
            ["푸켓", "phuket"],
        ],
        [
            "th-cnx",
            "airport",
            "CNX",
            "치앙마이 국제공항",
            "치앙마이",
            98.9626,
            18.7668,
            ["chiang mai"],
        ],
        [
            "th-usm",
            "airport",
            "USM",
            "사무이 국제공항",
            "코사무이",
            100.0623,
            9.5478,
            ["사무이", "koh samui"],
        ],
        [
            "th-kbv",
            "airport",
            "KBV",
            "끄라비 국제공항",
            "끄라비",
            98.9862,
            8.0991,
            ["크라비", "krabi"],
        ],
        [
            "th-rassada-port",
            "port",
            "RASSADA",
            "라싸다항",
            "푸껫",
            98.414,
            7.872,
            ["푸켓", "phuket"],
        ],
        [
            "th-nathon-port",
            "port",
            "NATHON",
            "나톤항",
            "코사무이",
            99.934,
            9.535,
            ["사무이", "koh samui"],
        ],
        [
            "th-laem-chabang-port",
            "port",
            "LAEM CHABANG",
            "램차방항",
            "파타야",
            100.88,
            13.08,
            ["방콕", "촌부리", "pattaya"],
        ],
        [
            "th-krabi-port",
            "port",
            "KRABI",
            "끄라비항",
            "끄라비",
            98.93,
            8.04,
            ["크라비", "krabi"],
        ],
        [
            "th-ao-nang-port",
            "port",
            "AO NANG",
            "아오낭항",
            "끄라비",
            98.81,
            8.03,
            ["크라비", "ao nang"],
        ],
    ],
    US: [
        [
            "us-lax",
            "airport",
            "LAX",
            "로스앤젤레스 국제공항",
            "로스앤젤레스",
            -118.4085,
            33.9416,
            ["엘에이", "los angeles"],
        ],
        [
            "us-sfo",
            "airport",
            "SFO",
            "샌프란시스코 국제공항",
            "샌프란시스코",
            -122.379,
            37.6213,
            ["san francisco"],
        ],
        [
            "us-jfk",
            "airport",
            "JFK",
            "존 F. 케네디 국제공항",
            "뉴욕",
            -73.7781,
            40.6413,
            ["new york"],
        ],
        [
            "us-ewr",
            "airport",
            "EWR",
            "뉴어크 리버티 국제공항",
            "뉴욕",
            -74.1745,
            40.6895,
            ["뉴어크", "new york", "newark"],
        ],
        [
            "us-las",
            "airport",
            "LAS",
            "해리 리드 국제공항",
            "라스베이거스",
            -115.1522,
            36.084,
            ["라스베가스", "las vegas"],
        ],
        [
            "us-hnl",
            "airport",
            "HNL",
            "다니엘 K. 이노우에 국제공항",
            "호놀룰루",
            -157.9224,
            21.3187,
            ["하와이", "honolulu", "hawaii"],
        ],
        [
            "us-sea",
            "airport",
            "SEA",
            "시애틀 터코마 국제공항",
            "시애틀",
            -122.3088,
            47.4502,
            ["seattle"],
        ],
        [
            "us-mia",
            "airport",
            "MIA",
            "마이애미 국제공항",
            "마이애미",
            -80.2906,
            25.7959,
            ["miami"],
        ],
        [
            "us-los-angeles-port",
            "port",
            "LOS ANGELES",
            "로스앤젤레스항",
            "로스앤젤레스",
            -118.264,
            33.74,
            ["엘에이", "los angeles"],
        ],
        [
            "us-miami-port",
            "port",
            "MIAMI",
            "마이애미항",
            "마이애미",
            -80.177,
            25.774,
            ["miami"],
        ],
        [
            "us-manhattan-port",
            "port",
            "MANHATTAN",
            "맨해튼 크루즈 터미널",
            "뉴욕",
            -74.006,
            40.768,
            ["맨해튼", "new york"],
        ],
        [
            "us-san-francisco-port",
            "port",
            "SAN FRANCISCO",
            "샌프란시스코항",
            "샌프란시스코",
            -122.393,
            37.795,
            ["san francisco"],
        ],
        [
            "us-seattle-port",
            "port",
            "SEATTLE",
            "시애틀항",
            "시애틀",
            -122.35,
            47.61,
            ["seattle"],
        ],
        [
            "us-honolulu-port",
            "port",
            "HONOLULU",
            "호놀룰루항",
            "호놀룰루",
            -157.86,
            21.306,
            ["하와이", "honolulu", "hawaii"],
        ],
    ],
};

export const transportHubs: readonly TransportHub[] =
    supportedCountries.flatMap(({ code: countryCode }) =>
        hubSeeds[countryCode].map(
            ([id, kind, code, name, region, longitude, latitude, aliases]) => ({
                id,
                countryCode,
                kind,
                code,
                name,
                region,
                aliases: aliases ?? [],
                coordinates: { latitude, longitude },
            }),
        ),
    );

function normalizeSearchText(value: string) {
    return value.toLocaleLowerCase("ko-KR").replace(/[\s-]+/g, "");
}

export function getTransportHub(hubId: string) {
    return transportHubs.find(({ id }) => id === hubId);
}

export function getTransportHubs(
    countryCode: CountryCode,
    transportType: HubTransportType,
) {
    const kind: TransportHubKind =
        transportType === "flight" ? "airport" : "port";

    return transportHubs.filter(
        (hub) => hub.countryCode === countryCode && hub.kind === kind,
    );
}

export function findTransportHub(
    countryCode: CountryCode,
    transportType: HubTransportType,
    hubId: string | null | undefined,
) {
    if (!hubId) {
        return undefined;
    }

    return getTransportHubs(countryCode, transportType).find(
        (hub) => hub.id === hubId,
    );
}

export function searchTransportHubs(
    countryCode: CountryCode,
    transportType: HubTransportType,
    query: string,
) {
    const hubs = getTransportHubs(countryCode, transportType);
    const normalizedQuery = normalizeSearchText(query);

    if (!normalizedQuery) {
        return hubs.slice(0, 6);
    }

    return hubs.filter((hub) =>
        [hub.region, hub.name, hub.code, ...hub.aliases].some((value) =>
            normalizeSearchText(value).includes(normalizedQuery),
        ),
    );
}
